# -*- coding: utf-8 -*-
"""Ana Maria Escobar Roa - MatplotLibNumpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I3dWZ6lkshRl4ruespKwP1P3FYmOfrP7

# Problemas

## Problema 1 ($\leq $ 30 pts)
Inspeccionando las gráficas de las funciones mencionadas en el intervalo dado, clasificarlas según sean crecientes, estrictamente crecientes, decrecientes, estrictamente decrecientes o ninguna de las anteriores en el intervalo dado. Consulte las definiciones en su libro de cálculo favorito o en internet. 

1.   $x^4-2x^3$ en $[0,\frac{3}{2}]$
2.   $\log(x)$ en $[1,100]$ (log es logaritmo natural)
3.   $\frac{\log(x)}{x}$ en $[1,100]$.
4.   $\exp(\sin(x)+\cos(x))$ en $[0,\frac{1}{2}]$ . Recuerde que por defecto las funciones trigonométricas tiene su argumento en radianes. 
5.   $\frac{1}{\sqrt{x}}$ en $[0.0001,1]$

## Problema 2 ($\leq $ 10 pts)
Para cada una de las siguientes funciones encuentre intervalos, lo mayor posible, en donde la función es creciente y decreciente. 

1. $x^4-x^2$
2. $\exp(\sin(x))$

## Problema 3 ($\leq$ 60 pts)  
**Nota** (Datos reales $\leq$ 60 pts, ficticios $\leq$ 30 pts).

Consulte diferentes formas de presentar datos en
 
https://colab.research.google.com/notebooks/charts.ipynb#scrollTo=DrRCtocXe9SB
 
Seleccione algún conjunto de datos reales (preferiblemente locales) o ficticios y haga alguna visualización de los mismos, agregando algunos comentarios que se puedan deducir directamente de las gráficas mostradas.  Considere el ejemplo en las próximas dos celdas para leer un archivo .xls de su drive de google. Siga el enlace que aparece y copie la clave de texto en el campo de texto que aparece al ejecutar el código de la primera celda. Puede usar otros formatos o formas de importar datos. Consultar en internet. 
 
Con datos reales = 60%
Datos ficticios = 30%
"""

from google.colab import drive
from google.colab import files
from xlrd import open_workbook
import numpy as np
import matplotlib.pyplot as plt
drive.mount('/gdrive', force_remount=True)

dataFileName = 'ejemplodatos.xls'
dataFilePath = '/gdrive/MyDrive/Classroom/PyMN2022I/Datos/datos.xlsx'
book = open_workbook(dataFilePath)
sheet = book.sheet_by_index(0)
y = np.asarray(sheet.col_values(2,6,69))
x = np.asarray(sheet.col_values(1,6,69))
plt.plot(x,y)

"""# Soluciones

PROBLEMA 1

1.   $x^4-2x^3$ en $[0,\frac{3}{2}]$
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(0, 3/2, .01)
coeficientes=[0, 0, 0, -2, 1]
polinomio1=np.polynomial.Polynomial(coef=coeficientes)
plt.figure(figsize=(10, 5))
plt.plot(x, polinomio1(x), color='purple', linestyle='-', label='x^4-2x^3', linewidth=2, markersize=5)
legend = plt.legend(loc='upper left', shadow=True, fontsize='x-large')
plt.show()

"""Es DECRECIENTE en el intervalo [0, 3/2], ya que para cualquier punto x del intervalo, la derivada es negativa ( f'(x)≤0).

2.   $\log(x)$ en $[1,100]$
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(1, 100, 1)
p1= np.log(x)
plt.figure(figsize=(10, 5))
plt.plot(x, p1, color='pink', linestyle='-', label='ln(x)', linewidth=2, markersize=5)
legend = plt.legend(loc='upper left', shadow=True, fontsize='x-large')
plt.show()

"""Es CRECIENTE en el intervalo [1, 100], ya que para cualquier punto x del intervalo, la derivada es positiva ( f'(x)≥0).

3.   $\frac{\log(x)}{x}$ en $[1,100]$.
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(1, 100, .01)
p1= np.log(x)/x
plt.figure(figsize=(20, 1))
plt.plot(x, p1, color='blue', linestyle='-', label='ln(x)/x', linewidth=2, markersize=5)
legend = plt.legend(loc='upper left', shadow=True, fontsize='x-large')
plt.show()

"""Es DECRECIENTE en el intervalo [1, 100], ya que para cualquier punto x del intervalo, la derivada es negativa ( f'(x)≤0).

4.   $\exp(\sin(x)+\cos(x))$ en $[0,\frac{1}{2}]$ .
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(0, 1/2, .01)
p1= np.exp(np.sin(x)+np.cos(x))
plt.figure(figsize=(5, 5))
plt.plot(x, p1, color='orange', linestyle='-', label='exp(sin(x)+cos(x))', linewidth=2, markersize=5)
legend = plt.legend(loc='upper left', shadow=True, fontsize='x-large')
plt.show()

"""Es  ESTRICTAMENTE CRECIENTE en el intervalo [0, 3/2], ya que al tomar dos puntos cualesquiera, a y b, con a<b, f(a)<f(b).

5.   $\frac{1}{\sqrt{x}}$ en $[0.0001,1]$
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(0.0001, 1, .0001)
p1= 1/np.sqrt(x)
plt.figure(figsize=(5, 10))
plt.plot(x, p1, color='green', linestyle='-', label='1/√x', linewidth=2, markersize=5)
legend = plt.legend(loc='upper left', shadow=True, fontsize='x-large')
plt.show()

"""Es DECRECIENTE en el intervalo [0.00, 100], ya que para cualquier punto x del intervalo, la derivada es negativa ( f'(x)≤0).

PROBLEMA 2

1. $x^4-x^2$

DECRECIENTE
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(-2, -0.707, .01)
coeficientes=[0, 0, -1, 0, 1]
polinomio1=np.polynomial.Polynomial(coef=coeficientes)
plt.figure(figsize=(5, 5))
plt.plot(x, polinomio1(x), color='pink', linestyle='-', label='x^4-x^2', linewidth=2, markersize=5)
legend = plt.legend(loc='upper left', shadow=True, fontsize='x-large')
plt.show()

"""CRECIENTE"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(0.707, 2, .01)
coeficientes=[0, 0, -1, 0, 1]
polinomio1=np.polynomial.Polynomial(coef=coeficientes)
plt.figure(figsize=(5, 5))
plt.plot(x, polinomio1(x), color='blue', linestyle='-', label='x^4-x^2', linewidth=2, markersize=5)
legend = plt.legend(loc='upper left', shadow=True, fontsize='x-large')
plt.show()

"""2. $\exp(\sin(x))$

CRECIENTE
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange((-np.pi)/2, np.pi/2, .0001)
p1= np.exp(np.sin(x))
plt.figure(figsize=(10, 5))
plt.plot(x, p1, color='yellow', linestyle='-', label='exp(sin(x))', linewidth=2, markersize=5)
legend = plt.legend(loc='upper left', shadow=True, fontsize='x-large')
plt.show()

"""DECRECIENTE"""

import numpy as np
import matplotlib.pyplot as plt
x = np.arange(np.pi/2, (3*np.pi)/2, .0001)
p1= np.exp(np.sin(x))
plt.figure(figsize=(10, 5))
plt.plot(x, p1, color='red', linestyle='-', label='exp(sin(x))', linewidth=2, markersize=5)
legend = plt.legend(loc='upper left', shadow=True, fontsize='x-large')
plt.show()

"""PROBLEMA 3"""

from google.colab import drive
from google.colab import files
from xlrd import open_workbook
import numpy as np
import matplotlib.pyplot as plt
drive.mount('/gdrive', force_remount=True)

dataFileName = 'indempleo.xls'
dataFilePath = '/gdrive/MyDrive/Classroom/PyMN2022I/Datos/Ind_empleo_1958_2018.xlsx'
book = open_workbook(dataFilePath)
sheet = book.sheet_by_index(0)
y = np.asarray(sheet.col_values(0,12,28))
x = np.asarray(sheet.col_values(13,12,28))
plt.scatter(x,y, color='pink', linestyle='-', linewidth=3)

"""Gráfica de la Tasa de subempleo subjetivo con respecto al año entre 2002-2018. Tomado de:https://www.dane.gov.co/index.php/estadisticas-por-tema/mercado-laboral/empleo-y-desempleo
Link en drive del archivo: https://docs.google.com/spreadsheets/d/19MK5jvZC5cBQkgXUdxRlnUdqtx-MSNgJ/edit?usp=sharing&ouid=116989339472422436388&rtpof=true&sd=true
"""